"""TSM's issuer-reported 2025 cash flows and full daily ADR price history."""

from datetime import date, timedelta
from math import isclose
from unittest.mock import patch

import pandas as pd

from app.engine.metrics import compute_row
from app.pipeline import fetch_one
from app.models import FactSeries, Fundamentals, PriceHistory, PricePoint, Quote
from app.providers import prices
from app.providers.adr import normalize_tsm, normalize_tsm_shares
from app.providers.fundamentals import get_fundamentals
from app.providers.tsm_official import extract_annual_cash_flow, fill_tsm_cash_flow


FY = date(2025, 12, 31)


def _twd(value, end=FY):
    return FactSeries(tag="SEC", unit="TWD", points=[(end, value)])


def _sec():
    return Fundamentals(ticker="TSM", currency="TWD", fiscal_end=FY,
                        source="SEC IFRS", revenue=_twd(3_809_054_272_000),
                        operating_income=_twd(1_936_091_677_000),
                        operating_cash_flow=_twd(2_274_975_625_000),
                        shares_outstanding=25_930_000_000)


def test_tsm_2025_issuer_capex_fills_without_yahoo_and_calculates_all_fcf_metrics():
    with patch("app.providers.fundamentals.get_sec_fundamentals", return_value=_sec()):
        fund = get_fundamentals("TSM", allow_yahoo=False)
    assert fund.capex.latest() == 1_272_410_529_000
    assert "investor.tsmc.com" in fund.notes[-1]
    usd = normalize_tsm(fund, Quote(ticker="TSM", currency="USD", price=350),
                        .032, "test TWDUSD")
    history = PriceHistory(ticker="TSM", points=[
        PricePoint(d=date.today() - timedelta(days=90-i), close=300+i*.5)
        for i in range(91)
    ])
    row = compute_row("TSM", history=history,
                      quote=Quote(ticker="TSM", currency="USD", price=350), fund=usd)
    assert isclose(row.fcf_margin, .26320577875977297)
    assert row.fcf_yield is not None and row.fcf_yield > 0
    assert isclose(row.price_to_fcf, row.market_cap / row.fcf_fy0)
    assert row.return_3m is not None and row.return_3m > 0


def test_tsm_fx_invariance_and_no_fx_market_cap() -> None:
    fund = fill_tsm_cash_flow(_sec())
    quote = Quote(ticker="TSM", currency="USD", price=350)
    history = PriceHistory(ticker="TSM", points=[PricePoint(d=FY, close=350)])
    rows = [compute_row("TSM", history=history, quote=quote,
                        fund=normalize_tsm(fund, quote, rate, "test spot"))
            for rate in (.030, .034)]
    local = compute_row("TSM", history=history, quote=quote,
                        fund=normalize_tsm_shares(fund, quote))
    expected_cap = 350 * 25_930_000_000 / 5
    for row in (*rows, local):
        assert isclose(row.fcf_margin, .26320577875977297)
        assert isclose(row.market_cap, expected_cap)
        assert row.filing_currency == "TWD"
    assert local.currency == "USD" and local.fx_usd_per_twd is None
    assert isclose(local.fcf_fy0, 1_002_565_096_000)
    assert local.fcf_yield is None and local.price_to_fcf is None
    assert local.price_to_sales is None and local.ev_to_ebitda is None
    for rate, row in zip((.030, .034), rows):
        assert isclose(row.fcf_yield, fund.operating_cash_flow.latest() * rate / expected_cap - fund.capex.latest() * rate / expected_cap)
        assert isclose(row.price_to_fcf, expected_cap / (local.fcf_fy0 * rate))
        assert row.fx_usd_per_twd == rate


def test_live_tsm_pipeline_keeps_ads_market_cap_when_fx_endpoint_fails() -> None:
    quote = Quote(ticker="TSM", currency="USD", price=350)
    history = PriceHistory(ticker="TSM", points=[PricePoint(d=FY, close=350)])
    with patch("app.providers.prices.get_price_history", return_value=history), patch(
        "app.providers.quotes.get_quote", return_value=quote
    ), patch("app.providers.fundamentals.get_fundamentals", return_value=fill_tsm_cash_flow(_sec())), patch(
        "app.providers.fx.usd_per_twd", return_value=None
    ):
        row, error = fetch_one("TSM")
    assert error is None
    assert row is not None and isclose(row.market_cap, 350 * 25_930_000_000 / 5)
    assert isclose(row.fcf_margin, .26320577875977297)
    assert row.price_to_fcf is None and row.filing_currency == "TWD"


def test_misaligned_sec_capex_is_replaced_only_for_matching_fiscal_year():
    fund = _sec()
    fund.capex = _twd(956_006_536_000, date(2024, 12, 31))
    filled = fill_tsm_cash_flow(fund)
    assert filled.capex.latest_end() == FY
    fund.fiscal_end = date(2026, 12, 31)
    with patch("app.providers.tsm_official._download_facts", return_value=None):
        future = fill_tsm_cash_flow(fund)
    assert future.capex.latest_end() == date(2024, 12, 31)


def test_public_pdf_parser_reads_cash_flow_not_investing_cash_flow():
    pages = ["Consolidated financial statements for the YEARS ENDED DECEMBER 31, 2026 AND 2025"]
    pages += ["Net cash generated by operating activities 2,500,000,000 2,274,975,625\n"
              "Net cash used in investing activities (1,600,000,000) (1,144,393,407)\n"
              "Acquisitions of:\nProperty, plant and equipment (1,400,000,000) (1,272,410,529)\n"
              "Proceeds from disposal or redemption of:"]
    assert extract_annual_cash_flow(pages, 2026) == {
        "operating_cash_flow": 2_500_000_000_000, "capex": 1_400_000_000_000}
    assert extract_annual_cash_flow(pages, 2027) is None


def test_short_sina_price_response_uses_full_adjusted_sina_series():
    today = date.today()
    short = PriceHistory(ticker="TSM", points=[
        PricePoint(d=today - timedelta(days=60-i), close=250+i) for i in range(61)
    ], source="Sina")
    frame = pd.DataFrame({"date": pd.date_range(end=today, periods=400),
                          "close": [150+i/2 for i in range(400)]})
    with patch("app.providers.akshare_us.get_daily", return_value=frame), patch(
        "app.providers.prices._PIPELINE", [lambda _: short, prices._akshare_sina]
    ):
        history = prices.get_price_history("TSM", allow_yahoo=False)
    assert history.source == "akshare/Sina"
    # akshare forwards Sina's convention: splits are applied, dividends are not.
    assert history.used_adjusted is False
    assert history.points[-1].d == today
    assert history.window(91)[-1].d - history.window(91)[0].d >= timedelta(days=70)


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
            print("PASS", name)
