"""TSMC consolidated annual cash-flow facts, in reported TWD.

The 2025 issuer-reported values remain an exact-year fallback when its PDF is
unreachable. Later fiscal years are read from the issuer's PDF, never inferred
from the 2025 figures or from total investing cash flow.
"""

from __future__ import annotations

import io
import logging
import re
from datetime import date

import requests

from app import cache
from app.models import FactSeries, Fundamentals

log = logging.getLogger(__name__)
SOURCE = ("https://investor.tsmc.com/sites/ir/financial-report/{year}/"
          "TSMC%20{year}Q4%20Consolidated%20Financial%20Statements_E.pdf")
_REPORTED_2025 = {"operating_cash_flow": 2_274_975_625_000,
                  "capex": 1_272_410_529_000}  # NT$ thousands -> NT$
_REVENUE_2025 = 3_809_054_272_000


def _first_number(line: str) -> int | None:
    match = re.search(r"(?<!\d)\(?([\d]{1,3}(?:,[\d]{3}){2,})\)?", line)
    return int(match.group(1).replace(",", "")) if match else None


def extract_annual_cash_flow(pages: list[str], year: int) -> dict[str, int] | None:
    """Read current-year column on consolidated cash-flow pages only.

    Separately validate the PDF fiscal-year header. The word 'plant' occurs
    elsewhere in the report, and net investing cash flow is not capex.
    """
    header = " ".join(pages[:2]).upper()
    if not re.search(r"YEARS?\s+ENDED\s+DECEMBER\s+31,?\s*" + str(year), header):
        return None
    cash_pages = pages[:16]
    operating = capex = None
    for page in cash_pages:
        in_acquisitions = False
        for raw in page.splitlines():
            line = " ".join(raw.split())
            lower = line.lower()
            if "net cash generated by operating activities" in lower:
                operating = _first_number(line)
            if "acquisitions of:" in lower and "invest" not in lower:
                in_acquisitions = True
            if "proceeds from disposal" in lower:
                in_acquisitions = False
            if ("payments for acquisition of property, plant and equipment" in lower
                    or in_acquisitions and re.match(r"property, plant and equipment\s+", lower)):
                capex = _first_number(line)
    if not operating or not capex or capex >= operating * 5:
        return None
    return {"operating_cash_flow": operating * 1000, "capex": capex * 1000}


def _download_facts(year: int) -> dict[str, int] | None:
    key = f"cashflow:{year}"
    cached = cache.get("tsm_official", key, 7 * 86400)
    if cached:
        return cached
    url = SOURCE.format(year=year)
    try:
        response = requests.get(url, timeout=15, headers={"User-Agent": "FinanceRanker/1.0"})
        response.raise_for_status()
        if not response.content.startswith(b"%PDF") or len(response.content) > 40_000_000:
            return None
        from pypdf import PdfReader

        reader = PdfReader(io.BytesIO(response.content), strict=False)
        pages = [page.extract_text() or "" for page in reader.pages[:16]]
        facts = extract_annual_cash_flow(pages, year)
        if facts:
            cache.put("tsm_official", key, facts)
        return facts
    except Exception as exc:  # an unreadable issuer PDF is only a missing fallback
        log.info("TSMC issuer cash-flow PDF unavailable for %s: %s", year, exc)
        return None


def fill_tsm_cash_flow(fund: Fundamentals) -> Fundamentals:
    """Fill only missing or stale SEC cash figures for the same fiscal year."""
    end = fund.fiscal_end
    if fund.ticker != "TSM" or fund.currency != "TWD" or not end or end.month != 12 or end.day != 31:
        return fund
    fields = ("operating_cash_flow", "capex")
    missing = [field for field in fields if not (getattr(fund, field) and
               getattr(fund, field).aligned(end, tolerance_days=0) is not None)]
    if not missing:
        return fund
    # Cross-check the known 2025 issuer disclosure against SEC revenue.
    revenue = fund.revenue.aligned(end) if fund.revenue else None
    if end.year == 2025 and revenue and abs(revenue / _REVENUE_2025 - 1) > .05:
        return fund
    data = (_REPORTED_2025 if end == date(2025, 12, 31)
            else _download_facts(end.year))
    if not data:
        return fund
    result = fund.model_copy(deep=True)
    for field in missing:
        amount = data.get(field)
        if amount and amount > 0:
            setattr(result, field, FactSeries(tag="TSMC consolidated cash flows", unit="TWD",
                                              points=[(end, float(amount))]))
    result.notes.append("TSMC issuer FY" + str(end.year) + " cash-flow gap fill: " +
                        ", ".join(missing) + "; " + SOURCE.format(year=end.year))
    return result
